#! /bin/env -S sh

BUILD_FOLDER=build

set -e

# 0. Create build folder and ignore in versioning
mkdir -p $BUILD_FOLDER
echo '*' > $BUILD_FOLDER/.gitignore

# 1. Clean
(cd $BUILD_FOLDER && rm -f blink.o blink.elf blink.hex)

# 2. Compile
avr-gcc -mmcu=atmega64a -Os -DF_CPU=8000000UL -I/usr/lib/avr/include/ -c blink.c -o ./$BUILD_FOLDER/blink.o

# 3. Link
avr-gcc -mmcu=atmega64a ./$BUILD_FOLDER/blink.o -o ./$BUILD_FOLDER/blink.elf

# 4. Create hex file
avr-objcopy -O ihex -R .eeprom -R .fuse -R .lock -R .signature ./$BUILD_FOLDER/blink.elf ./$BUILD_FOLDER/blink.hex

# 5. Flash
avrdude -c usbasp -p m64 -B 16 -U flash:w:./$BUILD_FOLDER/blink.hex:i
